name: Create Test Release

on:
  push:
    tags:
      - testing_*

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Build
        run: |
          $ver = '${{ github.ref_name }}' -replace 'testing_'
          invoke-expression 'dotnet build --no-restore --configuration Debug --nologo -p:Version=$ver -p:FileVersion=$ver -p:AssemblyVersion=$ver'

      - name: write version into json
        run: |
          Write-Host '${{ github.ref_name }}'
          $ver = '${{ github.ref_name }}' -replace 'testing_'
          $path = './AetherSenseReduxReborn/bin/Debug/AetherSenseReduxReborn.json'
          $json = Get-Content -Raw $path | ConvertFrom-Json
          Write-host $json
          $json | Add-Member -Force -NotePropertyName "AssemblyVersion" -NotePropertyValue $ver
          $content = $json | ConvertTo-Json
          set-content -Path $path -Value $content

      - name: Archive
        run: Compress-Archive -Path AetherSenseReduxReborn/bin/Debug/* -DestinationPath AetherSenseReduxReborn.zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          path: |
            ./AetherSenseReduxReborn/bin/Debug/*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: AetherSenseReduxReborn ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./AetherSenseReduxReborn.zip
          asset_name: AetherSenseReduxReborn.zip
          asset_content_type: application/zip

      - name: Write out repo.json
        run: |
          $verT = '${{ github.ref_name }}'
          $ver = $verT -replace 'testing_'
          $path = './repo.json'
          $json = Get-Content -Raw $path | ConvertFrom-Json
          # $json[0].TestingAssemblyVersion = $ver          
          $json[0] | Add-Member -Force -NotePropertyName "TestingAssemblyVersion" -NotePropertyValue $ver
          # $json[0].DownloadLinkTesting = $json.DownloadLinkTesting -replace '[^/]+/AetherSenseReduxReborn.zip',"$verT/AetherSenseReduxReborn.zip"
          $json[0] | Add-Member -Force -NotePropertyName "DownloadLinkTesting"    -NotePropertyValue $json.DownloadLinkTesting -replace '[^/]+/AetherSenseReduxReborn.zip',"$ver/AetherSenseReduxReborn.zip"
          $content = $json | ConvertTo-Json
          set-content -Path $path -Value $content

      - name: Commit repo.json
        run: |
          git config --global user.name "Actions User"
          git config --global user.email "actions@github.com"
          git fetch origin master
          git branch -f master ${{ github.sha }}
          git checkout master
          git add repo.json
          git commit -m "[CI] Updating repo.json for ${{ github.ref_name }}" || true
          git push origin master
